import { useRef } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Avatar from "../components/Avatar";
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";

import Image from "next/image";
import { GoogleCloneLogo } from "../components/GoogleCloneLogo";
import Footer from "../components/Footer";

export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();

  const search = (e) => {
    e.preventDefault();

    const term = searchInputRef.current.value;
    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex justify-end w-full p-5 text-sm text-gray-700">
        {/* Left */}

        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link text-xl">Gmail</p>
          <p className="link text-xl">Bilder</p>

          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avatar */}
          <Avatar url="https://lh3.googleusercontent.com/-6ES5Dw2fsoY/YKa4g9tcDDI/AAAAAAAAAAg/YBgCaHz-_Ior3KC_lXDU0i2getbmAXoQQCEwYBhgLKtMDAL1OcqzF1vfmHGBleiPM5hXJ8iMNEEQDGhYrPKYmKm7FAwuq7sA3fG2fpqIsN-FQdDlWG3SLCeUdHmr1YQ7WOOXv-TGDkKgxInV6RvyaUL_AGi4jChElBbmYo-8kU4ffO3ctDJXO3KHeNMVfcyAymL85ALwBXyVFvFSXog7QadoAEHM2wGYbgfZJtXQaGAH5D4uMKuIVzYv7vG_bsfQhlermfhJjE95HmusHatWhYFRmVP0Us0q_kMpzjSiksKa4tP3lku1GQOjD2wjhe8oWwV1mMOPWfY59ErzwYmjm1Rv1vJbycKbbDvPYOIB6aTTYZxJGZmej7QVXN2grMpoMaC6MAacKiSHrtKyiI6ZdOOPdAnFohwHRSB9cjgSGNZYU100CZjNGiZUlXb9Y-53X6POCFAXR5ZKxXasBueVdpfZJfcu_PYbv-n6yUfRbUbjhY72E1oF_agYPOHHk2khpdrkGKImXIMJbNLPcDLeGR5CUilf4qwY2qxWkjPkL_-BbIdMe2kxQ57sDi5bUpVPyFKAY7KDqJhncALNzC6kckMj-HUNs8q3_KBThgl6bHlRe9Rxqh6_JiydLbduMQNF1PupUb8mHEHC77PWnj7Y0e2ITjWkw7Ke0hQY/w139-h140-p/117697176_625128418437238_1764737668208809646_n.jpg" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <GoogleCloneLogo />

        <div className="flex w-full mt-10 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center minSm:max-w-xl minLg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />
          <MicrophoneIcon className="h-5" />
        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 minMd:space-y-0 minMd:flex-row minMd:space-x-4">
          <button onClick={search} className="btn">
            Sök på Google
          </button>
          <button onClick={search} className="btn">
            Jag har tur
          </button>
        </div>
      </form>

      {/* Footer */}
      <Footer />
    </div>
  );
}
